name: StockMarket
version: 0.3.4_02
author: CrashGamesCrMc
main: io.github.crashgamescrmc.StockMarket.StockMarketPlugin
description: A minecraft plugin that adds a stock market.
depend: [Vault]

commands:
  sm:
    aliases: []
    description: The base stock market command.
    usage: /sm